### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by vwmattr** [spoonben/zombies#1]
```
20:38 ~/dev/git/zombies (master)$ grunt drone
Running "execute:drone" (execute) task
-> executing /Users/Matt/Dev/git/zombies/scripts/drone.js
module.js:355
  Module._extensions[extension](this, filename);
                           ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Matt/Dev/git/zombies/node_modules/rolling-spider/node_modules/noble/node_modules/xpc-connection/index.js:3:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
Warning: -> error 1 /Users/Matt/Dev/git/zombies/scripts/drone.js (82ms) Use --force to continue.

Aborted due to warnings.
```

**Comment by spoonben** [comment]
Are you using the rolling spider? Or are you using the bebop?

**Comment by spoonben** [comment]
Also what version of node are you running
